### ISSUE TITLE
Bug on somewhat large displays?

### ISSUE THREAD

**Issue by crea1** [vegaasen/www.vegaasen.com#20]
https://imgur.com/a/xPyZD

Looks like the mediaquery below is triggered even tough my display is only 1080p.
```css
@media (min-width: 1800px)
.fancy-wrapper .fancy-content {
    font-size: 2.3em;
    word-break: break-all;
    word-spacing: 10px;
}
```
